name: CI Pipeline

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3

    - name: Install
      run: npm install

    - name: Build
      run: npm run build || echo "No build step"

    - name: Test
      run: npm test || echo "No tests"

     # 🔐 Install Grype
    - name: Install Grype
      run: |
        curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh

    # 🔍 Scan and save JSON
    - name: Run Security Scan
      run: |
        grype . -o json > report.json

    # 📁 Upload report
    - name: Upload Report
      uses: actions/upload-artifact@v3
      with:
        name: vulnerability-report
        path: report.json

    # ❌ Fail if vulnerabilities found
    - name: Fail if vulnerabilities exist
      run: |
        if grep -q '"severity":"Critical"' report.json; then
          echo "Critical vulnerabilities found!"
          exit 1
        fi